### ISSUE TITLE
Embedding an array of structs

### ISSUE THREAD

**Issue by miohtama** [hubo1016/namedstruct#1]
Hi!

First I'd like to say great work with namedstruct! It is very beautiful and Pythonic solution to work with byte level structures.

Is it possible to embed array of inner structs? This is not immediately clear from the documentation. Consider something like:

```
record_hmac_frame = ns.struct(

    # 0x01 for this structure. if version is incompatible then skip record
    (ns.uint8, 'kind'),

    # HMAC of data - mainly used to protect against bitrot on NFC cards
    (ns.uint32, "hmac"),

    #512 - 5 bytes of data. If the actual payload takes less the rest of bytes should be padded out with zeroes for HMAC calculation.
    (ns.raw, "data"),
)


file_system = ns.nstruct(

    # 0x01 for this record structure. if incompatible then cannot read anything
    (ns.uint8, 'version'),

    # pointers to next free record, wraps around in circular manner when full
    (ns.uint8, 'next_free_record'),

    # array of latest records stored in this system
    (record_hmac_frame[16],),

    name="file_system",
    padding = 0,
)
```

**Comment by miohtama** [comment]
I figured it out. It was actually in my_base_array example. One had to use `my_struct_name[0]` syntax. For the future reference:

```
RecordChecksumFrame = ns.nstruct(

    # 0x00 empty
    # 0x01 for this structure. if version is incompatible then skip record
    (ns.uint8, 'kind'),

    # Checksum of data - mainly used to protect against bitrot on NFC cards. MD5
    (ns.uint32, "checksum"),

    # 512 - 5 bytes of data. If the actual payload takes less the rest of bytes should be padded out with zeroes for HMAC calculation.
    (ns.uint8[507], "data"),

    padding = 1,
    name="checksum_frame",
)


FileSystem = ns.nstruct(

    # 0x01 for this record structure. if incompatible then cannot read anything
    (ns.uint8, 'version'),

    # The max count of records on this FS
    (ns.uint8, 'total_records'),

    # pointers to next free record, wraps around in circular manner when full
    (ns.uint8, 'next_free_record'),

    # array of latest records stored in this system
    (RecordChecksumFrame[0], 'records'),

    name="file_system",
    padding = 1,
    size = lambda x: x.total_records,
)
```

**Comment by hubo1016** [comment]
Hi, it is OK to use a fix-sized array, the point is that a field of array type cannot be anonymous - if it has no name, there is no way to reference it. Simply give it a name.
There are three ways to define a field of array type:
A fix-sized array, which looks like record_hmac_frame[16], it always have a fixed length (16). If there are not enough elements in the list, the library automatically create new elements; if there are more, only first 16 elments are preserved.
A variable length array, which looks like RecordChecksumFrame[0]. It can contain any number of elements. On parsing, the correct length is determined by the struct size.
A _darray_ is an array with fixed length, but the length is calculated by other fields.

For an array of inner structs to parse correctly, the inner struct should have determined size: either all the fields have fixed size (primitives, fix-size arrays, etc.), or it has a _size_ option to calculate the correct size. For your first example, the _raw_ type can take any bytes, so it is impossible to find where that field ends. The second example is good (is it 512 instead of 507 though?). Or you may use "char[512]" if you prefer a bytes (str) type.

Also check if you have notice the _padding_ option, it may add unexpected padding bytes if you do not set padding = 1.

**Comment by miohtama** [comment]
Thank you for the clarification!
